### ISSUE TITLE
Need to install NordicARC

### ISSUE THREAD

**Issue by skrbcr** [skrbcr/almaqso#6]
To run `analysis.py`, you have to install `NordicARC`.
This module can be found at [UVMultiFit](https://github.com/onsala-space-observatory/UVMultiFit).
The installation guide is [provieded](https://github.com/onsala-space-observatory/UVMultiFit/blob/master/INSTALL.md).

```
Traceback (most recent call last):
  File "/opt/casa-6.6.3-22-py3.8.el8/lib/py/lib/python3.8/site-packages/casashell/private/init_system.py", line 236, in __evprop__
    exec(stmt)
  File "<string>", line 1, in <module>
  File "/opt/casa-6.6.3-22-py3.8.el8/lib/py/lib/python3.8/site-packages/casashell/private/init_system.py", line 173, in execfile
    newglob = run_path( filename, init_globals=globals )
  File "/opt/casa-6.6.3-22-py3.8.el8/lib/py/lib/python3.8/runpy.py", line 265, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/opt/casa-6.6.3-22-py3.8.el8/lib/py/lib/python3.8/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/opt/casa-6.6.3-22-py3.8.el8/lib/py/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "./tempfiles/uid___A002_Xd68367_X9885.ms.split.split.J2000-1748.spw_19.avg.noselfcal.kw_uvfit.py", line 1, in <module>
    from NordicARC import uvmultifit as uvm
ModuleNotFoundError: No module named 'NordicARC'

```

**Comment by skrbcr** [comment]
Write above in `README.md`!

**Comment by skrbcr** [comment]
We no longer have to modify like the above!
Instead, install `UVMultiFit` with the branch `develop`.
