### ISSUE TITLE
Bug at Step 5-3 of QSOanalysis

### ISSUE THREAD

**Issue by skrbcr** [skrbcr/almaqso#7]
An error occurred at Step 5-3 of `QSOanalysis`. I doubt the cause is Step 5-1 since no-avg is running into this problem (not found in the `CORRECTED_DATA` column) whereas `avg` is processed normally.

```
*** doSaveFlags ***
step:3
step:4
step:5
### field: J2000-1748, spw: 19 ###
step5-1
step5-2
step5-3 (1)
step5-7 (1)
step5-4 (1)
step5-4 (2)
step5-5 (1)
step5-3 (2)
step5-7 (2)
step5-4 (3)
step5-4 (4)
step5-1'
step5-3 (3)
CASA exits with a non-zero status : exception: <class 'RuntimeError'>

STDERR: ....10....20....30....40....50....60....70....80....90....100%
Calculating the coefficients now ...
done!
/usr/local/casa/casa-6.6.1-17-pipeline-2024.1.0.8/lib/py/lib/python3.8/site-packages/IPython/core/interactiveshell.py:965: UserWarning: Attempting to work in a virtualenv. If you encounter problems, please insta
  warn(
2024-11-20 10:45:17     WARN    MSTransformManager::checkCorrelatorPreaveraging The data has already been preaveraged by the correlator but further smoothing or averaging has been requested. Preaveraged SPWs are
2024-11-20 10:45:21     WARN    calibrater::setvi(bool,bool)    Forcing use of OLD VisibilityIterator.
/usr/local/casa/casa-6.6.1-17-pipeline-2024.1.0.8/lib/py/lib/python3.8/site-packages/IPython/core/interactiveshell.py:965: UserWarning: Attempting to work in a virtualenv. If you encounter problems, please insta
  warn(
uvmultifit - INFO - started
measurement - INFO - number of antennas = 47
measurement - INFO - You selected to apply primary-beam correction.
PLEASE, remember that the beam is being approximated
with a Gaussian, so it may not be very accuracte far
from the pointing direction.
measurement - INFO - an antenna diameter of 12.000m will be applied
measurement - INFO - spectral index #0 (1 of 1)
measurement - INFO - reading scans for spw 0
measurement - INFO - reading scan #3 (1 of 1), field: 0
measurement - INFO - reading took 0.06 seconds
measurement - INFO - there are 50 integrations (51750 visibs.) in spw 0
modeler - INFO - UVMultiFit compiled model(s) do not seem to exist yet.
modeler - INFO - going to compile models
modeler - INFO - executing: 'self.varfunc[0] = lambda p, nu: [0,0,p[0]]'
modeler - INFO - executing: 'self.compiledScaleFixed = lambda p, nu: 1.0 + 0.0'
modeler - INFO - going to run setModel
modeler - INFO - now fitting model
modeler - INFO - continuum mode fit
modeler - INFO - iteration #1: achieved ChiSq: 9.31674658e+10
modeler - INFO - iteration #2: achieved ChiSq: 1.15799597e+11
modeler - INFO - iteration #3: achieved ChiSq: 7.29940294e+10
modeler - INFO - iteration #4: achieved ChiSq: 5.52792884e+10
modeler - INFO - iteration #5: achieved ChiSq: 2.72258922e+10
modeler - INFO - iteration #6: achieved ChiSq: 9.00727727e+09
modeler - INFO - iteration #7: achieved ChiSq: 9.31674658e+10
modeler - INFO - iteration #8: achieved ChiSq: 2.72258922e+10
modeler - INFO - iteration #9: achieved ChiSq: 6.23443592e+08
modeler - INFO - iteration #10: achieved ChiSq: 9.31674658e+10
modeler - INFO - iteration #11: achieved ChiSq: 9.31674658e+10
modeler - INFO - iteration #12: achieved ChiSq: 3.58601277e+09
modeler - INFO - iteration #13: achieved ChiSq: 1.19569722e+08
modeler - INFO - iteration #14: achieved ChiSq: 9.31674658e+10
modeler - INFO - iteration #15: achieved ChiSq: 9.31674658e+10
modeler - INFO - iteration #16: achieved ChiSq: 6.41697430e+07
modeler - INFO - iteration #17: achieved ChiSq: 6.23443592e+08
modeler - INFO - iteration #18: achieved ChiSq: 1.50355040e+07
modeler - INFO - iteration #19: achieved ChiSq: 1.19569722e+08
modeler - INFO - iteration #20: achieved ChiSq: 2.03940664e+07
modeler - INFO - iteration #21: achieved ChiSq: 4.80940559e+07
modeler - INFO - iteration #22: achieved ChiSq: 1.29126459e+07
modeler - INFO - iteration #23: achieved ChiSq: 2.03940664e+07
modeler - INFO - iteration #24: achieved ChiSq: 1.27735402e+07
modeler - INFO - iteration #25: achieved ChiSq: 1.50355040e+07
modeler - INFO - iteration #26: achieved ChiSq: 1.25429593e+07
modeler - INFO - iteration #27: achieved ChiSq: 1.29126459e+07
modeler - INFO - iteration #28: achieved ChiSq: 1.25832163e+07
modeler - INFO - iteration #29: achieved ChiSq: 1.26527692e+07
modeler - INFO - iteration #30: achieved ChiSq: 1.25443295e+07
modeler - INFO - iteration #31: achieved ChiSq: 1.25791059e+07
modeler - INFO - iteration #32: achieved ChiSq: 1.25389548e+07
modeler - INFO - iteration #33: achieved ChiSq: 1.25443295e+07
modeler - INFO - iteration #34: achieved ChiSq: 1.25397847e+07
modeler - INFO - iteration #35: achieved ChiSq: 1.25404698e+07
modeler - INFO - iteration #36: achieved ChiSq: 1.25390767e+07
modeler - INFO - iteration #37: achieved ChiSq: 1.25394192e+07
modeler - INFO - iteration #38: achieved ChiSq: 1.25389425e+07
modeler - INFO - iteration #39: achieved ChiSq: 1.25390767e+07
modeler - INFO - iteration #40: achieved ChiSq: 1.25389303e+07
modeler - INFO - iteration #41: achieved ChiSq: 1.25389548e+07
modeler - INFO - iteration #42: achieved ChiSq: 1.25389318e+07
modeler - INFO - number of visibilities (deg.of freedom): 51750.0
modeler - INFO - the reduced Chi Squared will be set to 1 by re-scaling the visibility weights.
modeler - INFO - fit took 0.69 seconds
uvmultifit - INFO - fit done!
measurement - WARNING - writing to mosaics is experimental and may not work!
measurement - INFO - doing 'calibrated/uid___A002_Xd68367_X9885.ms.split.J2000-1748.spw_19.avg': spw 0, scan_id 3
measurement - INFO - CORRECTED_DATA written successfully
uvmultifit - INFO - started
measurement - INFO - number of antennas = 47
measurement - INFO - You selected to apply primary-beam correction.
PLEASE, remember that the beam is being approximated
with a Gaussian, so it may not be very accuracte far
from the pointing direction.
measurement - INFO - an antenna diameter of 12.000m will be applied
measurement - INFO - spectral index #0 (1 of 1)
measurement - INFO - reading scans for spw 0
measurement - INFO - reading scan #3 (1 of 1), field: 0
measurement - INFO - reading took 0.06 seconds
measurement - INFO - there are 50 integrations (51750 visibs.) in spw 0
modeler - INFO - UVMultiFit compiled model(s) do not seem to exist yet.
modeler - INFO - going to compile models
modeler - INFO - executing: 'self.varfunc[0] = lambda p, nu: [0,0,p[0]]'
modeler - INFO - executing: 'self.compiledScaleFixed = lambda p, nu: 1.0 + 0.0'
modeler - INFO - going to run setModel
modeler - INFO - now fitting model
modeler - INFO - continuum mode fit
modeler - INFO - iteration #1: achieved ChiSq: 9.31215038e+10
modeler - INFO - iteration #2: achieved ChiSq: 1.15748928e+11
modeler - INFO - iteration #3: achieved ChiSq: 7.29527750e+10
modeler - INFO - iteration #4: achieved ChiSq: 5.52427415e+10
modeler - INFO - iteration #5: achieved ChiSq: 2.71987604e+10
modeler - INFO - iteration #6: achieved ChiSq: 8.98956064e+09
modeler - INFO - iteration #7: achieved ChiSq: 9.31215038e+10
modeler - INFO - iteration #8: achieved ChiSq: 2.71987604e+10
modeler - INFO - iteration #9: achieved ChiSq: 6.15142095e+08
modeler - INFO - iteration #10: achieved ChiSq: 9.31215038e+10
modeler - INFO - iteration #11: achieved ChiSq: 9.31215038e+10
modeler - INFO - iteration #12: achieved ChiSq: 3.57300371e+09
modeler - INFO - iteration #13: achieved ChiSq: 1.15975792e+08
modeler - INFO - iteration #14: achieved ChiSq: 9.31215038e+10
modeler - INFO - iteration #15: achieved ChiSq: 9.31215038e+10
modeler - INFO - iteration #16: achieved ChiSq: 5.82220293e+07
modeler - INFO - iteration #17: achieved ChiSq: 6.15142095e+08
modeler - INFO - iteration #18: achieved ChiSq: 1.02646819e+07
modeler - INFO - iteration #19: achieved ChiSq: 1.15975792e+08
modeler - INFO - iteration #20: achieved ChiSq: 1.50347985e+07
modeler - INFO - iteration #21: achieved ChiSq: 4.39116796e+07
modeler - INFO - iteration #22: achieved ChiSq: 7.84760092e+06
modeler - INFO - iteration #23: achieved ChiSq: 1.50347985e+07
modeler - INFO - iteration #24: achieved ChiSq: 7.85560660e+06
modeler - INFO - iteration #25: achieved ChiSq: 1.02406649e+07
modeler - INFO - iteration #26: achieved ChiSq: 7.55147006e+06
modeler - INFO - iteration #27: achieved ChiSq: 7.85560660e+06
modeler - INFO - iteration #28: achieved ChiSq: 7.62450206e+06
modeler - INFO - iteration #29: achieved ChiSq: 7.62850490e+06
modeler - INFO - iteration #30: achieved ChiSq: 7.56922770e+06
modeler - INFO - iteration #31: achieved ChiSq: 7.57122912e+06
modeler - INFO - iteration #32: achieved ChiSq: 7.55565929e+06
modeler - INFO - iteration #33: achieved ChiSq: 7.55666000e+06
modeler - INFO - iteration #34: achieved ChiSq: 7.55239228e+06
modeler - INFO - iteration #35: achieved ChiSq: 7.55289263e+06
modeler - INFO - iteration #36: achieved ChiSq: 7.55163807e+06
modeler - INFO - iteration #37: achieved ChiSq: 7.55188824e+06
modeler - INFO - iteration #38: achieved ChiSq: 7.55148079e+06
modeler - INFO - iteration #39: achieved ChiSq: 7.55160587e+06
modeler - INFO - iteration #40: achieved ChiSq: 7.55145710e+06
modeler - INFO - iteration #41: achieved ChiSq: 7.55148079e+06
modeler - INFO - iteration #42: achieved ChiSq: 7.55145900e+06
modeler - INFO - number of visibilities (deg.of freedom): 51750.0
modeler - INFO - the reduced Chi Squared will be set to 1 by re-scaling the visibility weights.
modeler - INFO - fit took 0.73 seconds
uvmultifit - INFO - fit done!
measurement - WARNING - writing to mosaics is experimental and may not work!
measurement - INFO - doing 'calibrated/uid___A002_Xd68367_X9885.ms.split.J2000-1748.spw_19.avg': spw 0, scan_id 3
measurement - INFO - CORRECTED_DATA written successfully
uvmultifit - INFO - started
measurement - INFO - number of antennas = 47
measurement - INFO - You selected to apply primary-beam correction.
PLEASE, remember that the beam is being approximated
with a Gaussian, so it may not be very accuracte far
from the pointing direction.
measurement - INFO - an antenna diameter of 12.000m will be applied
measurement - INFO - spectral index #0 (1 of 1)
measurement - INFO - reading scans for spw 0
measurement - INFO - reading scan #3 (1 of 1), field: 0
measurement - INFO - reading took 0.73 seconds
measurement - INFO - there are 50 integrations (51750 visibs.) in spw 0
modeler - INFO - UVMultiFit compiled model(s) do not seem to exist yet.
modeler - INFO - going to compile models
modeler - INFO - executing: 'self.varfunc[0] = lambda p, nu: [0,0,p[0]]'
modeler - INFO - executing: 'self.compiledScaleFixed = lambda p, nu: 1.0 + 0.0'
modeler - INFO - going to run setModel
modeler - INFO - now fitting model
modeler - INFO - fitting channel 1 of 128 in spw 0
modeler - INFO - fitting channel 2 of 128 in spw 0
modeler - INFO - fitting channel 3 of 128 in spw 0
modeler - INFO - fitting channel 4 of 128 in spw 0
modeler - INFO - fitting channel 5 of 128 in spw 0
modeler - INFO - fitting channel 6 of 128 in spw 0
modeler - INFO - fitting channel 7 of 128 in spw 0
modeler - INFO - fitting channel 8 of 128 in spw 0
modeler - INFO - fitting channel 9 of 128 in spw 0
modeler - INFO - fitting channel 10 of 128 in spw 0
modeler - INFO - fitting channel 11 of 128 in spw 0
modeler - INFO - fitting channel 12 of 128 in spw 0
modeler - INFO - fitting channel 13 of 128 in spw 0
modeler - INFO - fitting channel 14 of 128 in spw 0
modeler - INFO - fitting channel 15 of 128 in spw 0
modeler - INFO - fitting channel 16 of 128 in spw 0
modeler - INFO - fitting channel 17 of 128 in spw 0
modeler - INFO - fitting channel 18 of 128 in spw 0
modeler - INFO - fitting channel 19 of 128 in spw 0
modeler - INFO - fitting channel 20 of 128 in spw 0
modeler - INFO - fitting channel 21 of 128 in spw 0
modeler - INFO - fitting channel 22 of 128 in spw 0
modeler - INFO - fitting channel 23 of 128 in spw 0
modeler - INFO - fitting channel 24 of 128 in spw 0
modeler - INFO - fitting channel 25 of 128 in spw 0
modeler - INFO - fitting channel 26 of 128 in spw 0
modeler - INFO - fitting channel 27 of 128 in spw 0
modeler - INFO - fitting channel 28 of 128 in spw 0
modeler - INFO - fitting channel 29 of 128 in spw 0
modeler - INFO - fitting channel 30 of 128 in spw 0
modeler - INFO - fitting channel 31 of 128 in spw 0
modeler - INFO - fitting channel 32 of 128 in spw 0
modeler - INFO - fitting channel 33 of 128 in spw 0
modeler - INFO - fitting channel 34 of 128 in spw 0
modeler - INFO - fitting channel 35 of 128 in spw 0
modeler - INFO - fitting channel 36 of 128 in spw 0
modeler - INFO - fitting channel 37 of 128 in spw 0
modeler - INFO - fitting channel 38 of 128 in spw 0
modeler - INFO - fitting channel 39 of 128 in spw 0
modeler - INFO - fitting channel 40 of 128 in spw 0
modeler - INFO - fitting channel 41 of 128 in spw 0
modeler - INFO - fitting channel 42 of 128 in spw 0
modeler - INFO - fitting channel 43 of 128 in spw 0
modeler - INFO - fitting channel 44 of 128 in spw 0
modeler - INFO - fitting channel 45 of 128 in spw 0
modeler - INFO - fitting channel 46 of 128 in spw 0
modeler - INFO - fitting channel 47 of 128 in spw 0
modeler - INFO - fitting channel 48 of 128 in spw 0
modeler - INFO - fitting channel 49 of 128 in spw 0
modeler - INFO - fitting channel 50 of 128 in spw 0
modeler - INFO - fitting channel 51 of 128 in spw 0
modeler - INFO - fitting channel 52 of 128 in spw 0
modeler - INFO - fitting channel 53 of 128 in spw 0
modeler - INFO - fitting channel 54 of 128 in spw 0
modeler - INFO - fitting channel 55 of 128 in spw 0
modeler - INFO - fitting channel 56 of 128 in spw 0
modeler - INFO - fitting channel 57 of 128 in spw 0
modeler - INFO - fitting channel 58 of 128 in spw 0
modeler - INFO - fitting channel 59 of 128 in spw 0
modeler - INFO - fitting channel 60 of 128 in spw 0
modeler - INFO - fitting channel 61 of 128 in spw 0
modeler - INFO - fitting channel 62 of 128 in spw 0
modeler - INFO - fitting channel 63 of 128 in spw 0
modeler - INFO - fitting channel 64 of 128 in spw 0
modeler - INFO - fitting channel 65 of 128 in spw 0
modeler - INFO - fitting channel 66 of 128 in spw 0
modeler - INFO - fitting channel 67 of 128 in spw 0
modeler - INFO - fitting channel 68 of 128 in spw 0
modeler - INFO - fitting channel 69 of 128 in spw 0
modeler - INFO - fitting channel 70 of 128 in spw 0
modeler - INFO - fitting channel 71 of 128 in spw 0
modeler - INFO - fitting channel 72 of 128 in spw 0
modeler - INFO - fitting channel 73 of 128 in spw 0
modeler - INFO - fitting channel 74 of 128 in spw 0
modeler - INFO - fitting channel 75 of 128 in spw 0
modeler - INFO - fitting channel 76 of 128 in spw 0
modeler - INFO - fitting channel 77 of 128 in spw 0
modeler - INFO - fitting channel 78 of 128 in spw 0
modeler - INFO - fitting channel 79 of 128 in spw 0
modeler - INFO - fitting channel 80 of 128 in spw 0
modeler - INFO - fitting channel 81 of 128 in spw 0
modeler - INFO - fitting channel 82 of 128 in spw 0
modeler - INFO - fitting channel 83 of 128 in spw 0
modeler - INFO - fitting channel 84 of 128 in spw 0
modeler - INFO - fitting channel 85 of 128 in spw 0
modeler - INFO - fitting channel 86 of 128 in spw 0
modeler - INFO - fitting channel 87 of 128 in spw 0
modeler - INFO - fitting channel 88 of 128 in spw 0
modeler - INFO - fitting channel 89 of 128 in spw 0
modeler - INFO - fitting channel 90 of 128 in spw 0
modeler - INFO - fitting channel 91 of 128 in spw 0
modeler - INFO - fitting channel 92 of 128 in spw 0
modeler - INFO - fitting channel 93 of 128 in spw 0
modeler - INFO - fitting channel 94 of 128 in spw 0
modeler - INFO - fitting channel 95 of 128 in spw 0
modeler - INFO - fitting channel 96 of 128 in spw 0
modeler - INFO - fitting channel 97 of 128 in spw 0
modeler - INFO - fitting channel 98 of 128 in spw 0
modeler - INFO - fitting channel 99 of 128 in spw 0
modeler - INFO - fitting channel 100 of 128 in spw 0
modeler - INFO - fitting channel 101 of 128 in spw 0
modeler - INFO - fitting channel 102 of 128 in spw 0
modeler - INFO - fitting channel 103 of 128 in spw 0
modeler - INFO - fitting channel 104 of 128 in spw 0
modeler - INFO - fitting channel 105 of 128 in spw 0
modeler - INFO - fitting channel 106 of 128 in spw 0
modeler - INFO - fitting channel 107 of 128 in spw 0
modeler - INFO - fitting channel 108 of 128 in spw 0
modeler - INFO - fitting channel 109 of 128 in spw 0
modeler - INFO - fitting channel 110 of 128 in spw 0
modeler - INFO - fitting channel 111 of 128 in spw 0
modeler - INFO - fitting channel 112 of 128 in spw 0
modeler - INFO - fitting channel 113 of 128 in spw 0
modeler - INFO - fitting channel 114 of 128 in spw 0
modeler - INFO - fitting channel 115 of 128 in spw 0
modeler - INFO - fitting channel 116 of 128 in spw 0
modeler - INFO - fitting channel 117 of 128 in spw 0
modeler - INFO - fitting channel 118 of 128 in spw 0
modeler - INFO - fitting channel 119 of 128 in spw 0
modeler - INFO - fitting channel 120 of 128 in spw 0
modeler - INFO - fitting channel 121 of 128 in spw 0
modeler - INFO - fitting channel 122 of 128 in spw 0
modeler - INFO - fitting channel 123 of 128 in spw 0
modeler - INFO - fitting channel 124 of 128 in spw 0
modeler - INFO - fitting channel 125 of 128 in spw 0
modeler - INFO - fitting channel 126 of 128 in spw 0
modeler - INFO - fitting channel 127 of 128 in spw 0
modeler - INFO - fitting channel 128 of 128 in spw 0
modeler - INFO - the reduced Chi Squared will be set to 1 by re-scaling the visibility weights.
modeler - INFO - fit took 120.29 seconds
uvmultifit - INFO - fit done!
measurement - WARNING - writing to mosaics is experimental and may not work!
measurement - INFO - doing 'calibrated/uid___A002_Xd68367_X9885.ms.split.J2000-1748.spw_19': spw 0, scan_id 3
2024-11-20 10:47:43     SEVERE  getcol::CORRECTED_DATA  Exception Reported: TableProxy::getColumn: column CORRECTED_DATA does not exist
Traceback (most recent call last):
  File "/usr/local/casa/casa-6.6.1-17-pipeline-2024.1.0.8/lib/py/lib/python3.8/site-packages/casashell/private/init_system.py", line 233, in __evprop__
    run_path( args[0], init_globals=exec_globals, run_name='__main__' )
  File "/usr/local/casa/casa-6.6.1-17-pipeline-2024.1.0.8/lib/py/lib/python3.8/runpy.py", line 265, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/usr/local/casa/casa-6.6.1-17-pipeline-2024.1.0.8/lib/py/lib/python3.8/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/local/casa/casa-6.6.1-17-pipeline-2024.1.0.8/lib/py/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/akimsans/almaqso/test/script_test_analysis.py", line 13, in <module>
    analysis(
  File "/home/akimsans/almaqso/../almaqso/almaqso/analysis.py", line 29, in analysis
    obj.uvfit_run(plot=True)
  File "/home/akimsans/almaqso/../almaqso/almaqso/QSOanalysis.py", line 757, in uvfit_run
    self.uvfit_uvmultifit(
  File "/home/akimsans/almaqso/../almaqso/almaqso/QSOanalysis.py", line 397, in uvfit_uvmultifit
    myfit = uvm.uvmultifit(
  File "/home/akimsans/.local/lib/python3.8/site-packages/NordicARC/uvmultifit.py", line 491, in uvmultifit
    ms.write_model(column, mdl)
  File "/home/akimsans/.local/lib/python3.8/site-packages/NordicARC/measurementset.py", line 821, in write_model
    moddata = tb2.getcol(column)
  File "/usr/local/casa/casa-6.6.1-17-pipeline-2024.1.0.8/lib/py/lib/python3.8/site-packages/casatools/table.py", line 838, in getcol
    return self._swigobj.getcol(columnname, startrow, nrow, rowincr)
  File "/usr/local/casa/casa-6.6.1-17-pipeline-2024.1.0.8/lib/py/lib/python3.8/site-packages/casatools/__casac__/table.py", line 2154, in getcol
    return _table.table_getcol(self, *args, **kwargs)
RuntimeError: TableProxy::getColumn: column CORRECTED_DATA does not exist
```

**Comment by skrbcr** [comment]
At Step 5-1, No-avg do `mstransform` whereas Avg do `split`. In my experience, `split` complements lacked columns. Using it in no-avg may solve the problem...???

**Comment by skrbcr** [comment]
> At Step 5-1, No-avg do `mstransform` whereas Avg do `split`. In my experience, `split` complements lacked columns. Using it in no-avg may solve the problem...???

Though this turns out to be nothing, I will keep this change because of the symmetry between avg and no-avg.

**Comment by skrbcr** [comment]
I noticed that avg do Step 5-2 `uvfit_createcol(dryrun=dryrun)` created `CORRECTED_DATA`:

```python
    # step5-2: create model column
    def uvfit_createcol(self, modelcol=True, dryrun=False):
        if not dryrun:
            kw_clearcal = {
                'vis': f'calibrated/{self.visname}.split.{self.field}.spw_{self.spw}',
                'addmodel': modelcol,
            }

            from casatasks import clearcal
            clearcal(**kw_clearcal)
```

Actually, [clearcal](https://casadocs.readthedocs.io/en/stable/api/tt/casatasks.calibration.clearcal.html) generates this column.
I'll try to add this Step to no-avg.

**Comment by skrbcr** [comment]
> I noticed that avg do Step 5-2 `uvfit_createcol(dryrun=dryrun)` created `CORRECTED_DATA`:
> 
> Actually, [clearcal](https://casadocs.readthedocs.io/en/stable/api/tt/casatasks.calibration.clearcal.html) generates this column. I'll try to add this Step to no-avg.

This seems good. The error resolved!
